### ISSUE TITLE
is allowed check works only with PHP 5.4

### ISSUE THREAD

**Issue by franz-josef-kaiser** [stephenharris/WordPress-Post-Type-Archive-Links#34]
Throws an notice as reported [in this issue on wp.org](https://wordpress.org/support/topic/plugin-broken-with-last-version-of-wp?replies=3#post-6762627) for the [`filter_input_array()`](https://github.com/stephenharris/WordPress-Post-Type-Archive-Links/blob/master/post-type-archive-links.php#L354-L363) as the 3rd arg is PHP 5.4+ only.

**Comment by stephenharris** [comment]
Yup, very old bug too (fixed with #31).
